
met:
    name: MetFilterRDF
    path: Base.Modules.METfilters
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year

muon:
    name: DQCDMuonSelectionRDF
    path: modules.muon_selection
    parameters:
        year: self.config.year


muonsv:
    name: DQCDMuonSVSelectionRDF
    path: modules.muonsv_selection
    parameters:
        gen_mass: 2


jet_smearing:
    name: jetSmearerRDF
    path: Corrections.JME.smearing
    parameters:
        year: self.config.year
        isMC: self.dataset.process.isMC
        jerTag: self.config.year
        isUL: self.config.get_aux('isUL', self.dataset.has_tag('ul'))
        ispreVFP: self.config.get_aux('ispreVFP', False)


jet_smear_val:
    name: jetVarRDF
    path: Corrections.JME.smearing
    parameters:
        isMC: self.dataset.process.isMC

jec:
    name: jecProviderRDF
    path: Corrections.JME.jec
    parameters:
        year: self.config.year
        isMC: self.dataset.process.isMC
        isUL: self.config.get_aux('isUL', self.dataset.has_tag('ul'))
        ispreVFP: self.config.get_aux('ispreVFP', False)

jec_values:
    name: jecVarRDF
    path: Corrections.JME.jec
    parameters:
        year: self.config.year
        isMC: self.dataset.process.isMC
        jec_sources: [FlavorQCD]
        


met_smearing:
    name: metSmearerRDF
    path: Corrections.JME.smearing
    parameters:
        isMC: self.dataset.process.isMC


jet:
    name: DQCDJetSelectionRDF
    path: modules.jet_selection
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year
        jet_id: loose

bdt_inference_a:
    name: DQCDULBDTNoJet
    path: DQCD.Modules.BDTULinferenceNoJet
    parameters:
        isMC: self.dataset.process.isMC
        scenario: A

bdt_inference_b1:
    name: DQCDULBDTNoJet
    path: DQCD.Modules.BDTULinferenceNoJet
    parameters:
        isMC: self.dataset.process.isMC
        scenario: B1

######bdt:
    ######name: DQCDBDTSelectionRDF
    ######path: modules.bdt_selection
    ######parameters:
        ######bdt_name: bdt
        ######bdt_cut_value: 0.99
        #######bdt_cut_value: 0.0



trig:
    name: DQCDTriggerSelectionRDF
    path: modules.muonsv_selection
    parameters:
        gen_mass: 2


puweight:
    name: puWeightParkingRDF
    path: modules.puWeight
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year
        isUL: self.config.get_aux('isUL', self.dataset.has_tag('ul'))

pujetid:
    name: DQCDPUjetID_SFRDF
    path: modules.DQCD_SF
    parameters:
        year: self.config.year
        isMC: self.dataset.process.isMC
        isUL: self.config.get_aux('isUL', self.dataset.has_tag('ul'))
        ispreVFP: self.config.get_aux("isPreVFP", False)

idsf:
    name: DQCDIdSF_RDF
    path: modules.DQCD_SF
    parameters:
        isMC: self.dataset.process.isMC
        isUL: self.config.get_aux('isUL', self.dataset.has_tag('ul'))


trigsf:
    name: DQCDTrigSF_RDF
    path: modules.DQCD_SF
    parameters:
        isMC: self.dataset.process.isMC
        isUL: self.config.get_aux('isUL', self.dataset.has_tag('ul'))
