process_name: background
method: envelope
functions: polynomial, exponential, powerlaw
fit_parameters:
    polynomial_order: 1
    p0: 0, -5, 5

# process_name: background
# method: exponential


# process_name: background
# method: powerlaw
