chi2:
    name: DummyMinChi2RDF
    path: modules.muonsv_selection
    parameters:
        year: self.config.year

#TODO readd for 2024
#trigsf:
#    name: DQCDTrigSF_alltriggers_RDF
#    path: modules.DQCD_SF
#    parameters:
#        isMC: self.dataset.process.isMC
#        isUL: self.config.get_aux('isUL', self.dataset.has_tag('ul'))

loose:
    name: DQCDLooseMuonSelectionRDF
    path: modules.muonsv_selection
    parameters:
        gen_mass: 2

#TODO readd for 2024
#idsf:
#    name: DQCDIdSF_RDF
#    path: modules.DQCD_SF
#    parameters:
#        isMC: self.dataset.process.isMC
#        isUL: self.config.get_aux('isUL', self.dataset.has_tag('ul'))

bdtsf:
    name: DQCDBDTSFRDF
    path: modules.DQCD_SF
    parameters:
        process_name: self.dataset.process.name

########################################

bdt_inference_a:
    name: DQCDULBDTNoJet
    path: DQCD.Modules.BDTULinference2024_Mu10orDoubleMu_noMET
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year
        bdt_name: bdt_scenarioA_onlymu

#TODO readd for 2024
#prescaleWeight:
#    name: DQCDPrescaleWeight_RDF
#    path: modules.prescaleWeight
#    parameters:
#        isMC: self.dataset.process.isMC
