chi2:
    name: DummyMinChi2RDF
    path: modules.muonsv_selection
    parameters:
        year: self.config.year

trigsf:
    name: DQCDTrigSF_RDF
    path: modules.DQCD_SF
    parameters:
        isMC: self.dataset.process.isMC
        isUL: self.config.get_aux('isUL', self.dataset.has_tag('ul'))

#bdt_inference_a:
#    name: DQCDULBDTNoJet
#    path: DQCD.Modules.BDTULinferenceNoJet
#    parameters:
#        isMC: self.dataset.process.isMC
#        scenario: A
#        bdt_name: bdt_scenarioA_nojetsel
