chi2:
    name: DummyMinChi2RDF
    path: modules.muonsv_selection
    parameters:
        year: self.config.year

trigsf:
    name: DQCDTrigSF_RDF
    path: modules.DQCD_SF
    parameters:
        isMC: self.dataset.process.isMC
        isUL: self.config.get_aux('isUL', self.dataset.has_tag('ul'))

rew:
    name: DQCDReweighingRDF
    path: modules.reweighing
    parameters:
        input_ctau: self.config.get_ctau_from_dataset_name(self.dataset.dataset, '/')
        output_ctau: self.config.get_ctau_from_dataset_name(self.dataset.name)
        displaced_pdgid: 9900015
        do_reweighing: self.dataset.has_tag('rew')

#bdt_inference_a:
#    name: DQCDULBDTNoJet
#    path: DQCD.Modules.BDTULinferenceNoJet
#    parameters:
#        isMC: self.dataset.process.isMC
#        scenario: A
#        bdt_name: bdt_scenarioA_nojetsel
