background:
    process_name: background
    x_range: 1.28, 1.38
    method: polynomial
    fit_parameters:
        order: 1
        p0: 0, -1, 1

signal:
    process_name: signal
    method: voigtian
    x_range: 1.28, 1.38


# process_name: background
# method: exponential


# process_name: background
# method: powerlaw
