background:
    process_name: background
    x_range: 0, 100
    #x_range: 1.2635, 1.3965
    method: polynomial
    fit_parameters:
        order: 1
        p0: 0, -1, 1

signal:
    process_name: signal
    method: voigtian
    x_range: 1.2635, 1.3965


# process_name: background
# method: exponential


# process_name: background
# method: powerlaw
