#scenarioA_mpi_4_mA_1p33_ctau_10:
    #singlev_cat1: False
    ##singlev_cat2: False
    #singlev_cat3: False
    #singlev_cat4: False
    #singlev_cat5: False
    #singlev_cat6: True
    #multiv_cat1: True
    #multiv_cat2: True
    #multiv_cat3: False
    #multiv_cat4: True
    #multiv_cat5: True
    ##multiv_cat6: True

hzdzd_mzd_8_ctau_100:
    singlev_cat1: False
    singlev_cat2: True
    singlev_cat3: False
    singlev_cat4: False
    singlev_cat5: False
    singlev_cat6: True
    multiv_cat1: False
    multiv_cat2: True
    multiv_cat3: False
    multiv_cat4: True
    multiv_cat5: True
    multiv_cat6: True


hzdzd_mzd_8_ctau_1:
    singlev_cat1: False
    singlev_cat2: True
    singlev_cat3: False
    singlev_cat4: False
    singlev_cat5: False
    singlev_cat6: True
    multiv_cat1: False
    multiv_cat2: True
    multiv_cat3: False
    multiv_cat4: True
    multiv_cat5: True
    multiv_cat6: True
