met:
    name: MetFilterRDF
    path: Base.Filters.METfilters
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year

muon:
    name: DQCDMuonSelectionRDF
    path: modules.muon_selection
    parameters:
        year: self.config.year


muonsv:
    name: DQCDMuonSVSelectionRDF
    path: modules.muonsv_selection
    parameters:
        gen_mass: 2


trig:
    name: DQCDTriggerSelectionRDF
    path: modules.muonsv_selection
    parameters:
        gen_mass: 2

loose:
    name: DQCDLooseMuonSelectionRDF
    path: modules.muonsv_selection
    parameters:
        gen_mass: 2


puweight:
    name: puWeightParkingRDF
    path: modules.puWeight
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year
        isUL: self.config.get_aux('isUL', self.dataset.has_tag('ul'))

idsf:
    name: DQCDIdSF_RDF
    path: modules.DQCD_SF
    parameters:
        isMC: self.dataset.process.isMC
        isUL: self.config.get_aux('isUL', self.dataset.has_tag('ul'))


trigsf:
    name: DQCDTrigSF_RDF
    path: modules.DQCD_SF
    parameters:
        isMC: self.dataset.process.isMC
        isUL: self.config.get_aux('isUL', self.dataset.has_tag('ul'))


jet_smearing:
    name: jetSmearerRDF
    path: Corrections.JME.smearing
    parameters:
        year: self.config.year
        isMC: self.dataset.process.isMC
        jerTag: self.config.year
        isUL: self.config.get_aux('isUL', self.dataset.has_tag('ul'))
        ispreVFP: self.config.get_aux('ispreVFP', False)


jet_smear_val:
    name: jetVarRDF
    path: Corrections.JME.smearing
    parameters:
        isMC: self.dataset.process.isMC


met_smearing:
    name: metSmearerRDF
    path: Corrections.JME.smearing
    parameters:
        isMC: self.dataset.process.isMC


bdt_inference_a_nojet:
    name: DQCDULBDTNoJet
    path: DQCD.Modules.BDTULinferenceNoJet
    parameters:
        isMC: self.dataset.process.isMC
        scenario: A
        bdt_name: bdt_scenarioA_nojet

bdt_inference_a:
    name: DQCDULBDTOnlyMu
    path: DQCD.Modules.BDTULinferenceOnlyMu
    parameters:
        isMC: self.dataset.process.isMC
        scenario: A


#bdt_cut_loose:
    #name: DQCDBDTSelectionRDF
    #path: modules.bdt_selection
    #parameters:
        #bdt_name: bdt_scenarioA
        #bdt_cut_value: 0.7

#bdt_cut_tight:
    #name: DQCDBDTSelectionRDF
    #path: modules.bdt_selection
    #parameters:
        #bdt_name: bdt_scenarioA
        #bdt_cut_value: 0.98
