muon:
    name: DQCDMuonSelectionRDF
    path: modules.muon_selection
    parameters:
        year: self.config.year


jet:
    name: DQCDJetSelectionRDF
    path: modules.jet_selection
    parameters:
        year: self.config.year
        jet_id: loose


bdt:
    name: DQCDBDTSelectionRDF
    path: modules.bdt_selection
    parameters:
        bdt_name: xgb0__m_2p0_ctau_10p0_xiO_1p0_xiL_1p0
        # bdt_cut_value: 0.9994
        bdt_cut_value: 0.0


muonsv:
    name: DQCDMuonSVSelectionRDF
    path: modules.muonsv_selection
    parameters:
        gen_mass: 2


#puweight:
    #name: puWeightParkingRDF
    #path: modules.puWeight
    #parameters:
        #isMC: self.dataset.process.isMC
        #year: self.config.year
        #isUL: self.dataset.has_tag('ul')
