scenarioA_mpi_4_mA_1p33_ctau_0p1:
    singlev_cat3: False
    singlev_cat4: False
    singlev_cat5: True
    singlev_cat6: True
    multiv_cat1: True
    multiv_cat2: True
    multiv_cat3: True
    multiv_cat4: True
    multiv_cat5: True
    multiv_cat6: True

scenarioA_mpi_10_mA_3p33_ctau_1p0:
    singlev_cat3: False
    singlev_cat4: False
    singlev_cat5: True
    singlev_cat6: True
    multiv_cat1: True
    multiv_cat2: True
    multiv_cat3: True
    multiv_cat4: True
    multiv_cat5: True
    multiv_cat6: True

scenarioB1_mpi_1_mA_0p33_ctau_10:
    singlev_cat3: False
    singlev_cat4: False
    singlev_cat5: True
    singlev_cat6: True
    multiv_cat1: True
    multiv_cat2: True
    multiv_cat3: True
    multiv_cat4: True
    multiv_cat5: True
    multiv_cat6: True

scenarioB1_mpi_4_mA_0p80_ctau_100:
    singlev_cat3: True
    singlev_cat4: True
    singlev_cat5: True
    singlev_cat6: True
    multiv_cat1: True
    multiv_cat2: True
    multiv_cat3: True
    multiv_cat4: True
    multiv_cat5: True
    multiv_cat6: True



