scenarioA_mpi_4_mA_0p40_ctau_0p1:
    singlev_cat1: False
    singlev_cat2: False
    singlev_cat3: False
    singlev_cat4: False
    singlev_cat5: False
    singlev_cat6: False
    multiv_cat1: False
    multiv_cat2: False
    multiv_cat3: False
    multiv_cat4: False
    multiv_cat5: False
    multiv_cat6: False

scenarioA_mpi_4_mA_0p40_ctau_10:
    singlev_cat1: False
    singlev_cat2: False
    singlev_cat3: False
    singlev_cat4: False
    singlev_cat5: False
    singlev_cat6: False
    multiv_cat1: False
    multiv_cat2: False
    multiv_cat3: False
    multiv_cat4: False
    multiv_cat5: False
    multiv_cat6: False

scenarioA_mpi_4_mA_0p40_ctau_100:
    singlev_cat1: False
    singlev_cat2: False
    singlev_cat3: False
    singlev_cat4: False
    singlev_cat5: False
    singlev_cat6: False
    multiv_cat1: False
    multiv_cat2: False
    multiv_cat3: False
    multiv_cat4: False
    multiv_cat5: False
    multiv_cat6: False

scenarioA_mpi_4_mA_0p40_ctau_1p0:
    singlev_cat1: False
    singlev_cat2: False
    singlev_cat3: False
    singlev_cat4: False
    singlev_cat5: False
    singlev_cat6: False
    multiv_cat1: False
    multiv_cat2: False
    multiv_cat3: False
    multiv_cat4: False
    multiv_cat5: False
    multiv_cat6: False

scenarioA_mpi_4_mA_0p80_ctau_0p1:
    singlev_cat1: False
    singlev_cat2: False
    singlev_cat3: False
    singlev_cat4: False
    singlev_cat5: False
    singlev_cat6: False
    multiv_cat1: False
    multiv_cat2: False
    multiv_cat3: False
    multiv_cat4: False
    multiv_cat5: False
    multiv_cat6: False

scenarioA_mpi_4_mA_0p80_ctau_10:
    singlev_cat1: False
    singlev_cat2: False
    singlev_cat3: False
    singlev_cat4: False
    singlev_cat5: False
    singlev_cat6: False
    multiv_cat1: False
    multiv_cat2: False
    multiv_cat3: False
    multiv_cat4: False
    multiv_cat5: False
    multiv_cat6: False

scenarioA_mpi_4_mA_0p80_ctau_100:
    singlev_cat1: False
    singlev_cat2: False
    singlev_cat3: False
    singlev_cat4: False
    singlev_cat5: False
    singlev_cat6: False
    multiv_cat1: False
    multiv_cat2: False
    multiv_cat3: False
    multiv_cat4: False
    multiv_cat5: False
    multiv_cat6: False

scenarioA_mpi_4_mA_0p80_ctau_1p0:
    singlev_cat1: False
    singlev_cat2: False
    singlev_cat3: False
    singlev_cat4: False
    singlev_cat5: False
    singlev_cat6: False
    multiv_cat1: False
    multiv_cat2: False
    multiv_cat3: False
    multiv_cat4: False
    multiv_cat5: False
    multiv_cat6: False

scenarioA_mpi_4_mA_1p33_ctau_0p1:
    singlev_cat1: False
    singlev_cat2: False
    singlev_cat3: False
    singlev_cat4: False
    singlev_cat5: False
    singlev_cat6: False
    multiv_cat1: False
    multiv_cat2: False
    multiv_cat3: False
    multiv_cat4: False
    multiv_cat5: False
    multiv_cat6: False

scenarioA_mpi_4_mA_1p33_ctau_10:
    singlev_cat1: False
    singlev_cat2: False
    singlev_cat3: False
    singlev_cat4: False
    singlev_cat5: False
    singlev_cat6: False
    multiv_cat1: False
    multiv_cat2: False
    multiv_cat3: False
    multiv_cat4: False
    multiv_cat5: False
    multiv_cat6: False

scenarioA_mpi_4_mA_1p33_ctau_100:
    singlev_cat1: False
    singlev_cat2: False
    singlev_cat3: False
    singlev_cat4: False
    singlev_cat5: False
    singlev_cat6: False
    multiv_cat1: False
    multiv_cat2: False
    multiv_cat3: False
    multiv_cat4: False
    multiv_cat5: False
    multiv_cat6: False

scenarioA_mpi_4_mA_1p33_ctau_1p0:
    singlev_cat1: False
    singlev_cat2: False
    singlev_cat3: False
    singlev_cat4: False
    singlev_cat5: False
    singlev_cat6: False
    multiv_cat1: False
    multiv_cat2: False
    multiv_cat3: False
    multiv_cat4: False
    multiv_cat5: False
    multiv_cat6: False

scenarioA_mpi_4_mA_1p90_ctau_0p1:
    singlev_cat1: False
    singlev_cat2: False
    singlev_cat3: False
    singlev_cat4: False
    singlev_cat5: False
    singlev_cat6: False
    multiv_cat1: False
    multiv_cat2: False
    multiv_cat3: False
    multiv_cat4: False
    multiv_cat5: False
    multiv_cat6: False

scenarioA_mpi_4_mA_1p90_ctau_10:
    singlev_cat1: False
    singlev_cat2: False
    singlev_cat3: False
    singlev_cat4: False
    singlev_cat5: False
    singlev_cat6: False
    multiv_cat1: False
    multiv_cat2: False
    multiv_cat3: False
    multiv_cat4: False
    multiv_cat5: False
    multiv_cat6: False

scenarioA_mpi_4_mA_1p90_ctau_100:
    singlev_cat1: False
    singlev_cat2: False
    singlev_cat3: False
    singlev_cat4: False
    singlev_cat5: False
    singlev_cat6: False
    multiv_cat1: False
    multiv_cat2: False
    multiv_cat3: False
    multiv_cat4: False
    multiv_cat5: False
    multiv_cat6: False

scenarioA_mpi_4_mA_1p90_ctau_1p0:
    singlev_cat1: False
    singlev_cat2: False
    singlev_cat3: False
    singlev_cat4: False
    singlev_cat5: False
    singlev_cat6: False
    multiv_cat1: False
    multiv_cat2: False
    multiv_cat3: False
    multiv_cat4: False
    multiv_cat5: False
    multiv_cat6: False

