puweight:
    name: puWeightParkingRDF
    path: modules.puWeight
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year
        isUL: self.dataset.has_tag('ul')


filter_eff:
    name: DQCDFilterEfficiencyRDF
    path: modules.DQCD_SF
    parameters:
        process_name: self.dataset.process.name
